### ISSUE TITLE
Country entered during the Sign up is not getting displayed in the Onboarding page.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#53]
Description:

Country will be entered during the Sign up phase. But when we look at the Country field in the Onboarding page, no content is getting displayed. Do we need to prefill the Country field in the Onboarding page?

![image](https://user-images.githubusercontent.com/55895538/140291418-7c092030-45ca-42e1-a938-e2f8bdb97145.png)

![image](https://user-images.githubusercontent.com/55895538/140291928-a4928700-f880-4340-8a7c-2d107f81813e.png)

Community app --> Profile settings page

![image](https://user-images.githubusercontent.com/55895538/140292054-4f714063-9b47-4145-99af-16843c96825e.png)

**Comment by rakibansary** [comment]
A member can have one country specified in their profile settings page, and a different country specified in their Connect App Profile information.

When a user registers the country they specify is considered their home country (trait basic_info, homeCountryCode, competitionCountryCode).  The country set in Connect App seems to be their current location since we need to also specify "Normal Working Hours"

Whether we want to pre-populate Country in the onboarding app depends on what location (Home Country, or Current location) we want to store in the “Contact Details” page of the onboarding app. The country collected during registration is considered the members home country.

For reference here's the mapping

```csv
Contact Details Page (Onboarding App), Available in Connect App, Available in Profile App
Address Line 1, No, Yes
Address Line 2, No, Yes
City/District, No, Yes
Zip/Postal Code, No, Yes
Country, Yes, Yes
Start Time, Yes, No
End Time, Yes, No
```

I think 

a) We should pre-populate the Country field in the onboarding app using country entered by the member during registration
b) If user edits Country, we should update Country for both Connect App and CA Settings page

This is currently how it's implemented, except we aren't pre-populating country and we aren't storing data in fields homeCountryCode & competitionCountryCode in basic_info trait.

**Comment by Oanh-and-only-Oanh** [comment]
a) We should pre-populate the Country field in the onboarding app using country entered by the member during registration [YES]
b) If user edits Country, we should update Country for both Connect App and CA Settings page
[YES]

**Comment by rakibansary** [comment]
@dashu-baba can you please take this one.

**Comment by sandhiyakavi** [comment]
The country is displaying now
![image](https://user-images.githubusercontent.com/55895538/141275950-05dca92b-d15f-4cc8-a237-977f32f630b5.png)

Other details mentioned in https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/53#issuecomment-965543228  will be checked once the issue https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/137 is resolved

**Comment by coderhacker** [comment]
This is not fixed on production :

![image](https://user-images.githubusercontent.com/62358241/141312934-23d4598d-574e-4451-82ea-ddef9ec2f778.png)

CC @lakshmiathreya

**Comment by lakshmiathreya** [comment]
@coderhacker - pls show Country being set for this handle on the Profile page so we can show that Country has indeed been saved for this user.

**Comment by coderhacker** [comment]
Hi, @lakshmiathreya here is a screenshot of my profile where it's showing the correct country but onboard it's not showing.
![image](https://user-images.githubusercontent.com/62358241/141316712-5fae781e-96b4-4383-a0a2-e71babc95dce.png)

**Comment by lakshmiathreya** [comment]
Able to see Country now ... Seems like an intermittent issue 
<img width="1680" alt="Screenshot 2021-11-11 at 9 05 37 PM" src="https://user-images.githubusercontent.com/51733042/141326682-1638dd09-d020-4630-bdb6-7fa1bc4688c6.png">

**Comment by rakibansary** [comment]
@coderhacker to help me reproduce this, can you confirm if the account you were trying with was an older or a newly created acount?

We receive Country data from basic_info traits. If you are able to reproduce please take note of the network request shown in the screenshot below

![image](https://user-images.githubusercontent.com/1445965/141328265-194b5703-20c3-4786-8d84-efa3d637edd8.png)

**Comment by SathyaJayabal** [comment]
verified on prod, I can see country on the onboarding flow
<img width="1440" alt="Screenshot 2021-11-12 at 11 08 42 AM" src="https://user-images.githubusercontent.com/58783823/141415894-1b95853d-10a3-4235-8bb9-7b204cf46e62.png">
